#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Dec 09 14:37:48 EST 2019
# SW Build 2615518 on Fri Aug  9 15:53:29 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim distance_tb_behav -key {Behavioral:sim_1:Functional:distance_tb} -tclbatch distance_tb.tcl -view /afs/athena.mit.edu/user/j/e/jeana/6111project/sos/distance_tb_behav.wcfg -log simulate.log"
xsim distance_tb_behav -key {Behavioral:sim_1:Functional:distance_tb} -tclbatch distance_tb.tcl -view /afs/athena.mit.edu/user/j/e/jeana/6111project/sos/distance_tb_behav.wcfg -log simulate.log

